// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ChannelSendMessage.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct IGPChannelSendMessage: SwiftProtobuf.RequestMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var igpRequest: IGPRequest {
    get {return _storage._igpRequest ?? IGPRequest()}
    set {_uniqueStorage()._igpRequest = newValue}
  }
  /// Returns true if `igpRequest` has been explicitly set.
  public var hasIgpRequest: Bool {return _storage._igpRequest != nil}
  /// Clears the value of `igpRequest`. Subsequent reads from it will return its default value.
  public mutating func clearIgpRequest() {_uniqueStorage()._igpRequest = nil}

  public var igpMessageType: IGPRoomMessageType {
    get {return _storage._igpMessageType}
    set {_uniqueStorage()._igpMessageType = newValue}
  }

  public var igpRoomID: Int64 {
    get {return _storage._igpRoomID}
    set {_uniqueStorage()._igpRoomID = newValue}
  }

  public var igpMessage: String {
    get {return _storage._igpMessage}
    set {_uniqueStorage()._igpMessage = newValue}
  }

  public var igpAttachment: String {
    get {return _storage._igpAttachment}
    set {_uniqueStorage()._igpAttachment = newValue}
  }

  public var igpLocation: IGPRoomMessageLocation {
    get {return _storage._igpLocation ?? IGPRoomMessageLocation()}
    set {_uniqueStorage()._igpLocation = newValue}
  }
  /// Returns true if `igpLocation` has been explicitly set.
  public var hasIgpLocation: Bool {return _storage._igpLocation != nil}
  /// Clears the value of `igpLocation`. Subsequent reads from it will return its default value.
  public mutating func clearIgpLocation() {_uniqueStorage()._igpLocation = nil}

  public var igpContact: IGPRoomMessageContact {
    get {return _storage._igpContact ?? IGPRoomMessageContact()}
    set {_uniqueStorage()._igpContact = newValue}
  }
  /// Returns true if `igpContact` has been explicitly set.
  public var hasIgpContact: Bool {return _storage._igpContact != nil}
  /// Clears the value of `igpContact`. Subsequent reads from it will return its default value.
  public mutating func clearIgpContact() {_uniqueStorage()._igpContact = nil}

  public var igpReplyTo: Int64 {
    get {return _storage._igpReplyTo}
    set {_uniqueStorage()._igpReplyTo = newValue}
  }

  public var igpForwardFrom: IGPRoomMessageForwardFrom {
    get {return _storage._igpForwardFrom ?? IGPRoomMessageForwardFrom()}
    set {_uniqueStorage()._igpForwardFrom = newValue}
  }
  /// Returns true if `igpForwardFrom` has been explicitly set.
  public var hasIgpForwardFrom: Bool {return _storage._igpForwardFrom != nil}
  /// Clears the value of `igpForwardFrom`. Subsequent reads from it will return its default value.
  public mutating func clearIgpForwardFrom() {_uniqueStorage()._igpForwardFrom = nil}

  public var igpRandomID: Int64 {
    get {return _storage._igpRandomID}
    set {_uniqueStorage()._igpRandomID = newValue}
  }

  public var igpAdditionalType: Int32 {
    get {return _storage._igpAdditionalType}
    set {_uniqueStorage()._igpAdditionalType = newValue}
  }

  public var igpAdditionalData: String {
    get {return _storage._igpAdditionalData}
    set {_uniqueStorage()._igpAdditionalData = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct IGPChannelSendMessageResponse: SwiftProtobuf.ResponseMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var igpResponse: IGPResponse {
    get {return _storage._igpResponse ?? IGPResponse()}
    set {_uniqueStorage()._igpResponse = newValue}
  }
  /// Returns true if `igpResponse` has been explicitly set.
  public var hasIgpResponse: Bool {return _storage._igpResponse != nil}
  /// Clears the value of `igpResponse`. Subsequent reads from it will return its default value.
  public mutating func clearIgpResponse() {_uniqueStorage()._igpResponse = nil}

  public var igpRoomID: Int64 {
    get {return _storage._igpRoomID}
    set {_uniqueStorage()._igpRoomID = newValue}
  }

  public var igpRoomMessage: IGPRoomMessage {
    get {return _storage._igpRoomMessage ?? IGPRoomMessage()}
    set {_uniqueStorage()._igpRoomMessage = newValue}
  }
  /// Returns true if `igpRoomMessage` has been explicitly set.
  public var hasIgpRoomMessage: Bool {return _storage._igpRoomMessage != nil}
  /// Clears the value of `igpRoomMessage`. Subsequent reads from it will return its default value.
  public mutating func clearIgpRoomMessage() {_uniqueStorage()._igpRoomMessage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension IGPChannelSendMessage: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "IGPChannelSendMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_request"),
    2: .standard(proto: "IGP_message_type"),
    3: .standard(proto: "IGP_room_id"),
    4: .standard(proto: "IGP_message"),
    5: .standard(proto: "IGP_attachment"),
    6: .standard(proto: "IGP_location"),
    7: .standard(proto: "IGP_contact"),
    8: .standard(proto: "IGP_reply_to"),
    9: .standard(proto: "IGP_forward_from"),
    10: .standard(proto: "IGP_random_id"),
    11: .standard(proto: "IGP_additional_type"),
    12: .standard(proto: "IGP_additional_data"),
  ]

  fileprivate class _StorageClass {
    var _igpRequest: IGPRequest? = nil
    var _igpMessageType: IGPRoomMessageType = .text
    var _igpRoomID: Int64 = 0
    var _igpMessage: String = String()
    var _igpAttachment: String = String()
    var _igpLocation: IGPRoomMessageLocation? = nil
    var _igpContact: IGPRoomMessageContact? = nil
    var _igpReplyTo: Int64 = 0
    var _igpForwardFrom: IGPRoomMessageForwardFrom? = nil
    var _igpRandomID: Int64 = 0
    var _igpAdditionalType: Int32 = 0
    var _igpAdditionalData: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpRequest = source._igpRequest
      _igpMessageType = source._igpMessageType
      _igpRoomID = source._igpRoomID
      _igpMessage = source._igpMessage
      _igpAttachment = source._igpAttachment
      _igpLocation = source._igpLocation
      _igpContact = source._igpContact
      _igpReplyTo = source._igpReplyTo
      _igpForwardFrom = source._igpForwardFrom
      _igpRandomID = source._igpRandomID
      _igpAdditionalType = source._igpAdditionalType
      _igpAdditionalData = source._igpAdditionalData
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpRequest)
        case 2: try decoder.decodeSingularEnumField(value: &_storage._igpMessageType)
        case 3: try decoder.decodeSingularInt64Field(value: &_storage._igpRoomID)
        case 4: try decoder.decodeSingularStringField(value: &_storage._igpMessage)
        case 5: try decoder.decodeSingularStringField(value: &_storage._igpAttachment)
        case 6: try decoder.decodeSingularMessageField(value: &_storage._igpLocation)
        case 7: try decoder.decodeSingularMessageField(value: &_storage._igpContact)
        case 8: try decoder.decodeSingularInt64Field(value: &_storage._igpReplyTo)
        case 9: try decoder.decodeSingularMessageField(value: &_storage._igpForwardFrom)
        case 10: try decoder.decodeSingularInt64Field(value: &_storage._igpRandomID)
        case 11: try decoder.decodeSingularInt32Field(value: &_storage._igpAdditionalType)
        case 12: try decoder.decodeSingularStringField(value: &_storage._igpAdditionalData)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpRequest {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._igpMessageType != .text {
        try visitor.visitSingularEnumField(value: _storage._igpMessageType, fieldNumber: 2)
      }
      if _storage._igpRoomID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpRoomID, fieldNumber: 3)
      }
      if !_storage._igpMessage.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpMessage, fieldNumber: 4)
      }
      if !_storage._igpAttachment.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpAttachment, fieldNumber: 5)
      }
      if let v = _storage._igpLocation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
      if let v = _storage._igpContact {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }
      if _storage._igpReplyTo != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpReplyTo, fieldNumber: 8)
      }
      if let v = _storage._igpForwardFrom {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      }
      if _storage._igpRandomID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpRandomID, fieldNumber: 10)
      }
      if _storage._igpAdditionalType != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpAdditionalType, fieldNumber: 11)
      }
      if !_storage._igpAdditionalData.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpAdditionalData, fieldNumber: 12)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPChannelSendMessage, rhs: IGPChannelSendMessage) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._igpRequest != rhs_storage._igpRequest {return false}
        if _storage._igpMessageType != rhs_storage._igpMessageType {return false}
        if _storage._igpRoomID != rhs_storage._igpRoomID {return false}
        if _storage._igpMessage != rhs_storage._igpMessage {return false}
        if _storage._igpAttachment != rhs_storage._igpAttachment {return false}
        if _storage._igpLocation != rhs_storage._igpLocation {return false}
        if _storage._igpContact != rhs_storage._igpContact {return false}
        if _storage._igpReplyTo != rhs_storage._igpReplyTo {return false}
        if _storage._igpForwardFrom != rhs_storage._igpForwardFrom {return false}
        if _storage._igpRandomID != rhs_storage._igpRandomID {return false}
        if _storage._igpAdditionalType != rhs_storage._igpAdditionalType {return false}
        if _storage._igpAdditionalData != rhs_storage._igpAdditionalData {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension IGPChannelSendMessageResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "IGPChannelSendMessageResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_response"),
    2: .standard(proto: "IGP_room_id"),
    3: .standard(proto: "IGP_room_message"),
  ]

  fileprivate class _StorageClass {
    var _igpResponse: IGPResponse? = nil
    var _igpRoomID: Int64 = 0
    var _igpRoomMessage: IGPRoomMessage? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpResponse = source._igpResponse
      _igpRoomID = source._igpRoomID
      _igpRoomMessage = source._igpRoomMessage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpResponse)
        case 2: try decoder.decodeSingularInt64Field(value: &_storage._igpRoomID)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._igpRoomMessage)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpResponse {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._igpRoomID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpRoomID, fieldNumber: 2)
      }
      if let v = _storage._igpRoomMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPChannelSendMessageResponse, rhs: IGPChannelSendMessageResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._igpResponse != rhs_storage._igpResponse {return false}
        if _storage._igpRoomID != rhs_storage._igpRoomID {return false}
        if _storage._igpRoomMessage != rhs_storage._igpRoomMessage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
