// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: MplGetBillToken.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct IGPMplGetBillToken: SwiftProtobuf.RequestMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var igpRequest: IGPRequest {
    get {return _storage._igpRequest ?? IGPRequest()}
    set {_uniqueStorage()._igpRequest = newValue}
  }
  /// Returns true if `igpRequest` has been explicitly set.
  public var hasIgpRequest: Bool {return _storage._igpRequest != nil}
  /// Clears the value of `igpRequest`. Subsequent reads from it will return its default value.
  public mutating func clearIgpRequest() {_uniqueStorage()._igpRequest = nil}

  public var igpBillID: Int64 {
    get {return _storage._igpBillID}
    set {_uniqueStorage()._igpBillID = newValue}
  }

  public var igpPayID: Int64 {
    get {return _storage._igpPayID}
    set {_uniqueStorage()._igpPayID = newValue}
  }

  public var igpType: IGPMplGetBillToken.IGPType {
    get {return _storage._igpType}
    set {_uniqueStorage()._igpType = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum IGPType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case none // = 0
    case midTerm // = 1
    case lastTerm // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .none
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .none
      case 1: self = .midTerm
      case 2: self = .lastTerm
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .none: return 0
      case .midTerm: return 1
      case .lastTerm: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension IGPMplGetBillToken.IGPType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [IGPMplGetBillToken.IGPType] = [
    .none,
    .midTerm,
    .lastTerm,
  ]
}

#endif  // swift(>=4.2)

public struct IGPMplGetBillTokenResponse: SwiftProtobuf.ResponseMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var igpResponse: IGPResponse {
    get {return _storage._igpResponse ?? IGPResponse()}
    set {_uniqueStorage()._igpResponse = newValue}
  }
  /// Returns true if `igpResponse` has been explicitly set.
  public var hasIgpResponse: Bool {return _storage._igpResponse != nil}
  /// Clears the value of `igpResponse`. Subsequent reads from it will return its default value.
  public mutating func clearIgpResponse() {_uniqueStorage()._igpResponse = nil}

  public var igpStatus: Int32 {
    get {return _storage._igpStatus}
    set {_uniqueStorage()._igpStatus = newValue}
  }

  public var igpToken: String {
    get {return _storage._igpToken}
    set {_uniqueStorage()._igpToken = newValue}
  }

  public var igpExpireTime: Int32 {
    get {return _storage._igpExpireTime}
    set {_uniqueStorage()._igpExpireTime = newValue}
  }

  public var igpMessage: String {
    get {return _storage._igpMessage}
    set {_uniqueStorage()._igpMessage = newValue}
  }

  public var igpDiscountAmount: Int32 {
    get {return _storage._igpDiscountAmount}
    set {_uniqueStorage()._igpDiscountAmount = newValue}
  }

  public var igpOriginalAmount: Int32 {
    get {return _storage._igpOriginalAmount}
    set {_uniqueStorage()._igpOriginalAmount = newValue}
  }

  public var igpNewPayID: Int32 {
    get {return _storage._igpNewPayID}
    set {_uniqueStorage()._igpNewPayID = newValue}
  }

  public var igpOrganizationName: String {
    get {return _storage._igpOrganizationName}
    set {_uniqueStorage()._igpOrganizationName = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension IGPMplGetBillToken: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "IGPMplGetBillToken"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_request"),
    2: .standard(proto: "IGP_bill_id"),
    3: .standard(proto: "IGP_pay_id"),
    4: .standard(proto: "IGP_type"),
  ]

  fileprivate class _StorageClass {
    var _igpRequest: IGPRequest? = nil
    var _igpBillID: Int64 = 0
    var _igpPayID: Int64 = 0
    var _igpType: IGPMplGetBillToken.IGPType = .none

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpRequest = source._igpRequest
      _igpBillID = source._igpBillID
      _igpPayID = source._igpPayID
      _igpType = source._igpType
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpRequest)
        case 2: try decoder.decodeSingularInt64Field(value: &_storage._igpBillID)
        case 3: try decoder.decodeSingularInt64Field(value: &_storage._igpPayID)
        case 4: try decoder.decodeSingularEnumField(value: &_storage._igpType)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpRequest {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._igpBillID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpBillID, fieldNumber: 2)
      }
      if _storage._igpPayID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._igpPayID, fieldNumber: 3)
      }
      if _storage._igpType != .none {
        try visitor.visitSingularEnumField(value: _storage._igpType, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPMplGetBillToken, rhs: IGPMplGetBillToken) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._igpRequest != rhs_storage._igpRequest {return false}
        if _storage._igpBillID != rhs_storage._igpBillID {return false}
        if _storage._igpPayID != rhs_storage._igpPayID {return false}
        if _storage._igpType != rhs_storage._igpType {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension IGPMplGetBillToken.IGPType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NONE"),
    1: .same(proto: "MID_TERM"),
    2: .same(proto: "LAST_TERM"),
  ]
}

extension IGPMplGetBillTokenResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "IGPMplGetBillTokenResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_response"),
    2: .standard(proto: "IGP_status"),
    3: .standard(proto: "IGP_token"),
    4: .standard(proto: "IGP_expire_time"),
    5: .standard(proto: "IGP_message"),
    6: .standard(proto: "IGP_discount_amount"),
    7: .standard(proto: "IGP_original_amount"),
    8: .standard(proto: "IGP_new_pay_id"),
    9: .standard(proto: "IGP_organization_name"),
  ]

  fileprivate class _StorageClass {
    var _igpResponse: IGPResponse? = nil
    var _igpStatus: Int32 = 0
    var _igpToken: String = String()
    var _igpExpireTime: Int32 = 0
    var _igpMessage: String = String()
    var _igpDiscountAmount: Int32 = 0
    var _igpOriginalAmount: Int32 = 0
    var _igpNewPayID: Int32 = 0
    var _igpOrganizationName: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpResponse = source._igpResponse
      _igpStatus = source._igpStatus
      _igpToken = source._igpToken
      _igpExpireTime = source._igpExpireTime
      _igpMessage = source._igpMessage
      _igpDiscountAmount = source._igpDiscountAmount
      _igpOriginalAmount = source._igpOriginalAmount
      _igpNewPayID = source._igpNewPayID
      _igpOrganizationName = source._igpOrganizationName
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpResponse)
        case 2: try decoder.decodeSingularInt32Field(value: &_storage._igpStatus)
        case 3: try decoder.decodeSingularStringField(value: &_storage._igpToken)
        case 4: try decoder.decodeSingularInt32Field(value: &_storage._igpExpireTime)
        case 5: try decoder.decodeSingularStringField(value: &_storage._igpMessage)
        case 6: try decoder.decodeSingularInt32Field(value: &_storage._igpDiscountAmount)
        case 7: try decoder.decodeSingularInt32Field(value: &_storage._igpOriginalAmount)
        case 8: try decoder.decodeSingularInt32Field(value: &_storage._igpNewPayID)
        case 9: try decoder.decodeSingularStringField(value: &_storage._igpOrganizationName)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpResponse {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._igpStatus != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpStatus, fieldNumber: 2)
      }
      if !_storage._igpToken.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpToken, fieldNumber: 3)
      }
      if _storage._igpExpireTime != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpExpireTime, fieldNumber: 4)
      }
      if !_storage._igpMessage.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpMessage, fieldNumber: 5)
      }
      if _storage._igpDiscountAmount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpDiscountAmount, fieldNumber: 6)
      }
      if _storage._igpOriginalAmount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpOriginalAmount, fieldNumber: 7)
      }
      if _storage._igpNewPayID != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpNewPayID, fieldNumber: 8)
      }
      if !_storage._igpOrganizationName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpOrganizationName, fieldNumber: 9)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPMplGetBillTokenResponse, rhs: IGPMplGetBillTokenResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._igpResponse != rhs_storage._igpResponse {return false}
        if _storage._igpStatus != rhs_storage._igpStatus {return false}
        if _storage._igpToken != rhs_storage._igpToken {return false}
        if _storage._igpExpireTime != rhs_storage._igpExpireTime {return false}
        if _storage._igpMessage != rhs_storage._igpMessage {return false}
        if _storage._igpDiscountAmount != rhs_storage._igpDiscountAmount {return false}
        if _storage._igpOriginalAmount != rhs_storage._igpOriginalAmount {return false}
        if _storage._igpNewPayID != rhs_storage._igpNewPayID {return false}
        if _storage._igpOrganizationName != rhs_storage._igpOrganizationName {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
