// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: UserIVandGetScore.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct IGPUserIVandGetScore: SwiftProtobuf.RequestMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var igpRequest: IGPRequest {
    get {return _storage._igpRequest ?? IGPRequest()}
    set {_uniqueStorage()._igpRequest = newValue}
  }
  /// Returns true if `igpRequest` has been explicitly set.
  public var hasIgpRequest: Bool {return _storage._igpRequest != nil}
  /// Clears the value of `igpRequest`. Subsequent reads from it will return its default value.
  public mutating func clearIgpRequest() {_uniqueStorage()._igpRequest = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct IGPUserIVandGetScoreResponse: SwiftProtobuf.ResponseMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var igpResponse: IGPResponse {
    get {return _storage._igpResponse ?? IGPResponse()}
    set {_uniqueStorage()._igpResponse = newValue}
  }
  /// Returns true if `igpResponse` has been explicitly set.
  public var hasIgpResponse: Bool {return _storage._igpResponse != nil}
  /// Clears the value of `igpResponse`. Subsequent reads from it will return its default value.
  public mutating func clearIgpResponse() {_uniqueStorage()._igpResponse = nil}

  public var igpScore: Int32 {
    get {return _storage._igpScore}
    set {_uniqueStorage()._igpScore = newValue}
  }

  public var igpUserRank: Int32 {
    get {return _storage._igpUserRank}
    set {_uniqueStorage()._igpUserRank = newValue}
  }

  public var igpTotalRank: Int32 {
    get {return _storage._igpTotalRank}
    set {_uniqueStorage()._igpTotalRank = newValue}
  }

  public var igpScores: [IGPUserIVandGetScoreResponse.IGPIVandScore] {
    get {return _storage._igpScores}
    set {_uniqueStorage()._igpScores = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct IGPIVandScore: SwiftProtobuf.Message {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var igpID: Int32 = 0

    public var igpEnName: String = String()

    public var igpFaName: String = String()

    public var igpScore: Int32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension IGPUserIVandGetScore: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "IGPUserIVandGetScore"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_request"),
  ]

  fileprivate class _StorageClass {
    var _igpRequest: IGPRequest? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpRequest = source._igpRequest
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpRequest)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpRequest {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPUserIVandGetScore, rhs: IGPUserIVandGetScore) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._igpRequest != rhs_storage._igpRequest {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension IGPUserIVandGetScoreResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "IGPUserIVandGetScoreResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_response"),
    2: .standard(proto: "IGP_score"),
    3: .standard(proto: "IGP_user_rank"),
    4: .standard(proto: "IGP_total_rank"),
    5: .standard(proto: "IGP_scores"),
  ]

  fileprivate class _StorageClass {
    var _igpResponse: IGPResponse? = nil
    var _igpScore: Int32 = 0
    var _igpUserRank: Int32 = 0
    var _igpTotalRank: Int32 = 0
    var _igpScores: [IGPUserIVandGetScoreResponse.IGPIVandScore] = []

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpResponse = source._igpResponse
      _igpScore = source._igpScore
      _igpUserRank = source._igpUserRank
      _igpTotalRank = source._igpTotalRank
      _igpScores = source._igpScores
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpResponse)
        case 2: try decoder.decodeSingularInt32Field(value: &_storage._igpScore)
        case 3: try decoder.decodeSingularInt32Field(value: &_storage._igpUserRank)
        case 4: try decoder.decodeSingularInt32Field(value: &_storage._igpTotalRank)
        case 5: try decoder.decodeRepeatedMessageField(value: &_storage._igpScores)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpResponse {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._igpScore != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpScore, fieldNumber: 2)
      }
      if _storage._igpUserRank != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpUserRank, fieldNumber: 3)
      }
      if _storage._igpTotalRank != 0 {
        try visitor.visitSingularInt32Field(value: _storage._igpTotalRank, fieldNumber: 4)
      }
      if !_storage._igpScores.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._igpScores, fieldNumber: 5)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPUserIVandGetScoreResponse, rhs: IGPUserIVandGetScoreResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._igpResponse != rhs_storage._igpResponse {return false}
        if _storage._igpScore != rhs_storage._igpScore {return false}
        if _storage._igpUserRank != rhs_storage._igpUserRank {return false}
        if _storage._igpTotalRank != rhs_storage._igpTotalRank {return false}
        if _storage._igpScores != rhs_storage._igpScores {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension IGPUserIVandGetScoreResponse.IGPIVandScore: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = IGPUserIVandGetScoreResponse.protoMessageName + ".IGPIVandScore"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_id"),
    2: .standard(proto: "IGP_en_name"),
    3: .standard(proto: "IGP_fa_name"),
    4: .standard(proto: "IGP_score"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.igpID)
      case 2: try decoder.decodeSingularStringField(value: &self.igpEnName)
      case 3: try decoder.decodeSingularStringField(value: &self.igpFaName)
      case 4: try decoder.decodeSingularInt32Field(value: &self.igpScore)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.igpID != 0 {
      try visitor.visitSingularInt32Field(value: self.igpID, fieldNumber: 1)
    }
    if !self.igpEnName.isEmpty {
      try visitor.visitSingularStringField(value: self.igpEnName, fieldNumber: 2)
    }
    if !self.igpFaName.isEmpty {
      try visitor.visitSingularStringField(value: self.igpFaName, fieldNumber: 3)
    }
    if self.igpScore != 0 {
      try visitor.visitSingularInt32Field(value: self.igpScore, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IGPUserIVandGetScoreResponse.IGPIVandScore, rhs: IGPUserIVandGetScoreResponse.IGPIVandScore) -> Bool {
    if lhs.igpID != rhs.igpID {return false}
    if lhs.igpEnName != rhs.igpEnName {return false}
    if lhs.igpFaName != rhs.igpFaName {return false}
    if lhs.igpScore != rhs.igpScore {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
